### ISSUE TITLE
Add documentation for python bot sdk

### ISSUE THREAD

**Issue by Maay** [dialogs/python-bot-sdk#1]
Add to the readme file documentation and some examples for our Python Bot SDK. You can use as the reference our Java Bot SDK - https://docs.dlg.im/bots/java-bot.html
API reference - https://github.com/dialogs/api-schema

**Comment by Maay** [comment]
@ShellAddicted are you interested in this [bounty](https://www.bountysource.com/issues/64451098-add-documentation-for-python-bot-sdk)?

**Comment by ShellAddicted** [comment]
> @ShellAddicted are you interested in this [bounty](https://www.bountysource.com/issues/64451098-add-documentation-for-python-bot-sdk)?

Yes I am, but now I'm working on the sharing bot [bounty](https://www.bountysource.com/issues/64452951-sharebot-for-messenger)

I'll check this soon. (if this issue will be still open)

**Comment by nkt** [comment]
Already resolved: 
 - https://github.com/dialogs/python-bot-sdk/blob/master/README.md
 - https://dialogs.github.io/python-bot-sdk/
