### ISSUE TITLE
Add customProfile to python-bot-sdk

### ISSUE THREAD

**Issue by webngt** [dialogs/python-bot-sdk#11]
Currently it's not possible to fetch custom corporate profile with python-bot-sdk

To resolve this issue it is required to add customProfile property implementation to python-bot-sdk

It will also align python-bot-sdk with java-bot-sdk https://github.com/dialogs/java-bot-sdk/blob/master/src/main/java/im/dlg/botsdk/domain/User.java#L37

**Comment by Drymonade** [comment]
I've merged PR, now you can access customProfile field of User by particular method in Users stub. I'll describe it in docs. Closed.
